# Generated by Django 5.0.1 on 2024-03-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Name',
            new_name='name',
        ),
    ]
